Locatable locatable     # center is in middle of right lane
Expansion corner_points # corner points of floor sign detection (right lane only)
Expansion left_zone     # pedestrian search zone on left side
Expansion mid_zone      # pedestrian search zone on the road
Expansion right_zone    # pedestrian search zone on right side

bool pedes_is_passing   # pedestrian is on the road
bool pedes_is_waiting   # pedestrian is on either side of the road
